name: angel
description: A graphql starter application for Angel3 framework
publish_to: none 
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_configuration: ^4.1.0
  angel3_framework: ^4.2.0
  angel3_graphql: ^2.0.0
  angel3_jael: ^4.2.0
  angel3_production: ^3.1.0
  angel3_static: ^4.1.0
  angel3_validate: ^4.0.0
dev_dependencies:
  angel3_hot: ^4.2.0
  angel3_serialize_generator: ^4.2.0
  angel3_test: ^4.0.0
  graphql_generator2: ^2.1.0
  belatuk_pretty_logging: ^4.0.0
  build_runner: ^2.0.4 
  io: ^1.0.0 
  test: ^1.17.5
  lints: ^1.0.0 
