name: angel
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.10.0 <2.12.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.0.0 # Supports stateless authentication via JWT
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.0 # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_migration: ^2.0.0 # Migration runtime support
  angel_orm: ^2.0.0 # Migration runtime support
  angel_orm_postgres: ^1.0.0 # PostgreSQL support for Angel ORM
  angel_serialize: ^2.0.0 # Serialization runtime support
  angel_production: ^1.0.0 # Production application runner.
  angel_static: ^2.0.0 # Static file server
  angel_validate: ^2.0.0 # Allows for validation of input data
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_migration_runner: ^2.0.0 # Runs migrations
  angel_orm_generator: ^2.0.0 # Generates ORM libraries
  angel_serialize_generator: ^2.0.0 # Generates model serialization code
  angel_test: ^2.0.0 # Utilities for testing Angel servers.
  build_runner: ^1.0.0 # Runs builds
  io: ^0.3.2 # For pretty printing.
  pedantic: ^1.0.0 # Enforces Dart style conventions.
  test: ^1.0.0 # For unit testing.
dependency_overrides:
  angel_auth:
    path: ../angel/packages/auth
  angel_configuration:
    path: ../angel/packages/configuration
  angel_framework:
    path: ../angel/packages/framework
  angel_jael:
    path: ../angel/packages/jael/angel_jael
  angel_migration: 
    path: ../angel/packages/orm/angel_migration
  angel_orm: 
    path: ../angel/packages/orm/angel_orm
  angel_orm_postgres: 
    path: ../angel/packages/orm/angel_orm_postgres
  angel_serialize:
    path: ../angel/packages/serialize/angel_serialize
  angel_production:
    path: ../angel/packages/production
  angel_static:
    path: ../angel/packages/static
  angel_validate:
    path: ../angel/packages/validate
  angel_hot:
    path: ../angel/packages/hot
  angel_test:
    path: ../angel/packages/test
  angel_migration_runner:
    path: ../angel/packages/orm/angel_migration_runner
  angel_orm_generator:
    path: ../angel/packages/orm/angel_orm_generator
  angel_serialize_generator:
    path: ../angel/packages/serialize/angel_serialize_generator



