name: angel
version: 1.0.0
description: A boilerplate template for building Angel3 application with ORM enabled
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/dukefirehawk/boilerplates
dependencies:
  angel3_auth: ^4.0.0
  angel3_configuration: ^4.0.0
  angel3_framework: ^4.0.0
  angel3_jael: ^4.0.0
  angel3_migration: ^4.0.0-beta.1
  angel3_orm: ^4.0.0-beta.1
  angel3_orm_postgres: ^3.0.0-beta.1
  angel3_serialize: ^4.0.0
  angel3_production: ^3.0.0
  angel3_static: ^4.0.0
  angel3_validate: ^4.0.0
  angel3_pretty_logging: ^3.0.0
  optional: ^6.0.0-nullsafety.2
dev_dependencies:
  angel3_hot: ^4.0.0
  angel3_migration_runner: ^4.0.0-beta.1
  angel3_orm_generator: ^4.0.0-beta.1
  angel3_serialize_generator: ^4.0.0
  angel3_test: ^4.0.0
  build_runner: ^2.0.3
  io: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.7



