name: myapp
version: 4.0.0
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
homepage: https://github.com/dukefirehawk/angel
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_configuration: ^4.0.0 
  angel3_framework: ^4.0.0
  angel3_jael: ^4.0.0
  angel3_production: ^3.0.0
  angel3_static: ^4.0.0
  angel3_validate: ^4.0.0
  angel3_pretty_logging: ^3.0.0
dev_dependencies:
  angel3_hot: ^4.0.0
  angel3_test: ^4.0.0
  io: ^1.0.0 # For pretty printing.
  pedantic: ^1.11.0 # Enforces Dart style conventions.
  test: ^1.17.3 # For unit testing.




