name: angel
version: 1.0.0
description: A boilerplate template for building Angel3 application
publish_to: none
homepage: https://github.com/dukefirehawk/boilerplates
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_auth: ^4.0.0
  angel3_configuration: ^4.0.0 
  angel3_framework: ^4.0.0
  angel3_jael: ^4.0.0
  angel3_production: ^3.0.0
  angel3_static: ^4.0.0
  angel3_validate: ^4.0.0
  angel3_pretty_logging: ^3.0.0
dev_dependencies:
  angel3_hot: ^4.0.0
  angel3_test: ^4.0.0
  io: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.17.7




